### ISSUE TITLE
You can make the readme better by adding more details about your project here which would make your repo more readable

### ISSUE THREAD

**Issue by biswadeep-roy** [Soriful-Chalehin/SnapAd-Template#1]
You can enhance the readability of your repository by incorporating comprehensive details about the project in this README. Provide succinct yet informative content, ensuring that users can grasp the purpose and functionality of your project effortlessly.

**Comment by Soriful-Chalehin** [comment]
Thank you so much for creating this issuse, and your valuable comment. I already seen your some of projects. you are good at writing Docs, would you please contribute this project by creating README with your thought.  :)

**Comment by biswadeep-roy** [comment]
ok bro i'll fork it and ping u after making a pull request

**Comment by Soriful-Chalehin** [comment]
waiting for that! :)

**Comment by Soriful-Chalehin** [comment]
🙂
